# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nuance/dlg/v1/dlg_interface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from nuance.dlg.v1 import dlg_messages_pb2 as nuance_dot_dlg_dot_v1_dot_dlg__messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nuance/dlg/v1/dlg_interface.proto',
  package='nuance.dlg.v1',
  syntax='proto3',
  serialized_options=b'\n%com.nuance.coretech.dialog.v1.serviceP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!nuance/dlg/v1/dlg_interface.proto\x12\rnuance.dlg.v1\x1a\x1cgoogle/api/annotations.proto\x1a nuance/dlg/v1/dlg_messages.proto2\xac\x03\n\rDialogService\x12t\n\x05Start\x12\x1b.nuance.dlg.v1.StartRequest\x1a\x1c.nuance.dlg.v1.StartResponse\"0\x82\xd3\xe4\x93\x02*\"%/dlg/v1/start/{payload.model_ref.uri}:\x01*\x12q\n\x07\x45xecute\x12\x1d.nuance.dlg.v1.ExecuteRequest\x1a\x1e.nuance.dlg.v1.ExecuteResponse\"\'\x82\xd3\xe4\x93\x02!\"\x1c/dlg/v1/execute/{session_id}:\x01*\x12N\n\rExecuteStream\x12\x1a.nuance.dlg.v1.StreamInput\x1a\x1b.nuance.dlg.v1.StreamOutput\"\x00(\x01\x30\x01\x12\x62\n\x04Stop\x12\x1a.nuance.dlg.v1.StopRequest\x1a\x1b.nuance.dlg.v1.StopResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/dlg/v1/stop/{session_id}B)\n%com.nuance.coretech.dialog.v1.serviceP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,nuance_dot_dlg_dot_v1_dot_dlg__messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_DIALOGSERVICE = _descriptor.ServiceDescriptor(
  name='DialogService',
  full_name='nuance.dlg.v1.DialogService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=117,
  serialized_end=545,
  methods=[
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='nuance.dlg.v1.DialogService.Start',
    index=0,
    containing_service=None,
    input_type=nuance_dot_dlg_dot_v1_dot_dlg__messages__pb2._STARTREQUEST,
    output_type=nuance_dot_dlg_dot_v1_dot_dlg__messages__pb2._STARTRESPONSE,
    serialized_options=b'\202\323\344\223\002*\"%/dlg/v1/start/{payload.model_ref.uri}:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='nuance.dlg.v1.DialogService.Execute',
    index=1,
    containing_service=None,
    input_type=nuance_dot_dlg_dot_v1_dot_dlg__messages__pb2._EXECUTEREQUEST,
    output_type=nuance_dot_dlg_dot_v1_dot_dlg__messages__pb2._EXECUTERESPONSE,
    serialized_options=b'\202\323\344\223\002!\"\034/dlg/v1/execute/{session_id}:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ExecuteStream',
    full_name='nuance.dlg.v1.DialogService.ExecuteStream',
    index=2,
    containing_service=None,
    input_type=nuance_dot_dlg_dot_v1_dot_dlg__messages__pb2._STREAMINPUT,
    output_type=nuance_dot_dlg_dot_v1_dot_dlg__messages__pb2._STREAMOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Stop',
    full_name='nuance.dlg.v1.DialogService.Stop',
    index=3,
    containing_service=None,
    input_type=nuance_dot_dlg_dot_v1_dot_dlg__messages__pb2._STOPREQUEST,
    output_type=nuance_dot_dlg_dot_v1_dot_dlg__messages__pb2._STOPRESPONSE,
    serialized_options=b'\202\323\344\223\002\033\"\031/dlg/v1/stop/{session_id}',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIALOGSERVICE)

DESCRIPTOR.services_by_name['DialogService'] = _DIALOGSERVICE

# @@protoc_insertion_point(module_scope)
