# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nuance/nlu/v1/interpretation-common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nuance/nlu/v1/interpretation-common.proto',
  package='nuance.nlu.v1',
  syntax='proto3',
  serialized_options=b'\n\025com.nuance.rpc.nlu.v1B\031InterpretationCommonProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)nuance/nlu/v1/interpretation-common.proto\x12\rnuance.nlu.v1\"3\n\tTextRange\x12\x13\n\x0bstart_index\x18\x01 \x01(\r\x12\x11\n\tend_index\x18\x02 \x01(\r\"8\n\nAudioRange\x12\x15\n\rstart_time_ms\x18\x01 \x01(\r\x12\x13\n\x0b\x65nd_time_ms\x18\x02 \x01(\r*7\n\nEnumOrigin\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07GRAMMAR\x10\x01\x12\x0f\n\x0bSTATISTICAL\x10\x02\x42\x34\n\x15\x63om.nuance.rpc.nlu.v1B\x19InterpretationCommonProtoP\x01\x62\x06proto3'
)

_ENUMORIGIN = _descriptor.EnumDescriptor(
  name='EnumOrigin',
  full_name='nuance.nlu.v1.EnumOrigin',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GRAMMAR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATISTICAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=171,
  serialized_end=226,
)
_sym_db.RegisterEnumDescriptor(_ENUMORIGIN)

EnumOrigin = enum_type_wrapper.EnumTypeWrapper(_ENUMORIGIN)
UNKNOWN = 0
GRAMMAR = 1
STATISTICAL = 2



_TEXTRANGE = _descriptor.Descriptor(
  name='TextRange',
  full_name='nuance.nlu.v1.TextRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_index', full_name='nuance.nlu.v1.TextRange.start_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_index', full_name='nuance.nlu.v1.TextRange.end_index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=111,
)


_AUDIORANGE = _descriptor.Descriptor(
  name='AudioRange',
  full_name='nuance.nlu.v1.AudioRange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time_ms', full_name='nuance.nlu.v1.AudioRange.start_time_ms', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time_ms', full_name='nuance.nlu.v1.AudioRange.end_time_ms', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['TextRange'] = _TEXTRANGE
DESCRIPTOR.message_types_by_name['AudioRange'] = _AUDIORANGE
DESCRIPTOR.enum_types_by_name['EnumOrigin'] = _ENUMORIGIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextRange = _reflection.GeneratedProtocolMessageType('TextRange', (_message.Message,), {
  'DESCRIPTOR' : _TEXTRANGE,
  '__module__' : 'nuance.nlu.v1.interpretation_common_pb2'
  # @@protoc_insertion_point(class_scope:nuance.nlu.v1.TextRange)
  })
_sym_db.RegisterMessage(TextRange)

AudioRange = _reflection.GeneratedProtocolMessageType('AudioRange', (_message.Message,), {
  'DESCRIPTOR' : _AUDIORANGE,
  '__module__' : 'nuance.nlu.v1.interpretation_common_pb2'
  # @@protoc_insertion_point(class_scope:nuance.nlu.v1.AudioRange)
  })
_sym_db.RegisterMessage(AudioRange)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
