# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from nuance.nlu.v1 import runtime_pb2 as nuance_dot_nlu_dot_v1_dot_runtime__pb2


class RuntimeStub(object):
    """*
    Interpretation service. Use the Interpret procedure to request an
    interpretation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Interpret = channel.unary_unary(
                '/nuance.nlu.v1.Runtime/Interpret',
                request_serializer=nuance_dot_nlu_dot_v1_dot_runtime__pb2.InterpretRequest.SerializeToString,
                response_deserializer=nuance_dot_nlu_dot_v1_dot_runtime__pb2.InterpretResponse.FromString,
                )


class RuntimeServicer(object):
    """*
    Interpretation service. Use the Interpret procedure to request an
    interpretation.
    """

    def Interpret(self, request, context):
        """Starts an interpretation request and returns a response. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Interpret': grpc.unary_unary_rpc_method_handler(
                    servicer.Interpret,
                    request_deserializer=nuance_dot_nlu_dot_v1_dot_runtime__pb2.InterpretRequest.FromString,
                    response_serializer=nuance_dot_nlu_dot_v1_dot_runtime__pb2.InterpretResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nuance.nlu.v1.Runtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Runtime(object):
    """*
    Interpretation service. Use the Interpret procedure to request an
    interpretation.
    """

    @staticmethod
    def Interpret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nuance.nlu.v1.Runtime/Interpret',
            nuance_dot_nlu_dot_v1_dot_runtime__pb2.InterpretRequest.SerializeToString,
            nuance_dot_nlu_dot_v1_dot_runtime__pb2.InterpretResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
